/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tunipharma.gui;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import tunipharma.DAO.PharmacieDAO;
import tunipharma.entities.Pharmacie;
//import tunipharma.gui.ListPharmacieModel;

public class Admin_GererPharmacie extends javax.swing.JFrame {

    /**
     * Creates new form Admin_GererPharmacie
     */
    PharmacieDAO stdao = new PharmacieDAO();
    ListPharmacieModel model = new ListPharmacieModel();
    
     
    
    
    public Admin_GererPharmacie() {
        initComponents();        
      // ListPharmacieModel model =new ListPharmacieModel(stdao.DisplayPartiePharmacie());
       /* for (int i=0; i<(stdao.DisplayPartiePharmacie().size()) ; i++)
        {
            System.out.println(stdao.DisplayPartiePharmacie().get(i).getNom());
        }*/
        nb_pharma_label.setText(Integer.toString(model.getRowCount()));
       // add();
    }

   /* public void add()
    {
           DefaultTableModel tm = (DefaultTableModel) table.getModel();
       
       
        List<Pharmacie> services=new ArrayList<Pharmacie>();
        PharmacieDAO ser;
        ser=new PharmacieDAO();
       ser.DisplayPartiePharmacie();
       for (int i = 0; i < services.size(); i++)
       {
    tm.addRow(new Object[] {services.get(i).getNom(),services.get(i).getDescription(),services.get(i).getDateCreation(),services.get(i).getDateLimit(),services.get(i).getType(),services.get(i).getResponsableSociete().getNom(),services.get(i).getCatalogue().getNom()});
       
       }
        
    }*/
    /** 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        Delete_btn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        nb_pharma_label = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(610, 600));
        setPreferredSize(new java.awt.Dimension(600, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        table.setModel(model);
        jScrollPane2.setViewportView(table);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(0, 220, 470, 290);

        Delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Delete_btn);
        Delete_btn.setBounds(470, 280, 110, 50);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nombre Total des Pharmacies :");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(370, 190, 210, 14);

        nb_pharma_label.setForeground(new java.awt.Color(255, 255, 255));
        nb_pharma_label.setText("jLabel14");
        getContentPane().add(nb_pharma_label);
        nb_pharma_label.setBounds(550, 190, 40, 14);

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(450, 10, 130, 30);

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(450, 60, 130, 30);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(460, 510, 130, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tunipharma/image/Pharmacies.png"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(600, 800));
        jLabel3.setMinimumSize(new java.awt.Dimension(600, 800));
        jLabel3.setPreferredSize(new java.awt.Dimension(600, 590));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -20, 840, 610);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_btnActionPerformed
         model.remove_pharmacie(table.getSelectedRow());
         
        // model.stdao.deletePharmacie(jTable2.getSelectedRow());
    }//GEN-LAST:event_Delete_btnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        jButton1.setBorderPainted(false); 
jButton1.setContentAreaFilled(false); 
jButton1.setFocusPainted(false); 
jButton1.setOpaque(false);
       
        
Delete_btn.setBorderPainted(false); 
Delete_btn.setContentAreaFilled(false); 
Delete_btn.setFocusPainted(false); 
Delete_btn.setOpaque(false);        

jButton5.setBorderPainted(false); 
jButton5.setContentAreaFilled(false); 
jButton5.setFocusPainted(false); 
jButton5.setOpaque(false);

jButton6.setBorderPainted(false); 
jButton6.setContentAreaFilled(false); 
jButton6.setFocusPainted(false); 
jButton6.setOpaque(false);

        
Delete_btn.setBorderPainted(false); 
Delete_btn.setContentAreaFilled(false); 
Delete_btn.setFocusPainted(false); 
Delete_btn.setOpaque(false);  


// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        this.setVisible(true);
        FormProfilAdmin formadmin = new FormProfilAdmin();
        formadmin.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

           this.setVisible(false);
        Admin_Connexion adm =new Admin_Connexion();
        adm.setVisible(true);
                
// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        Admin_Accueil accueil = new Admin_Accueil();
        accueil.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_GererPharmacie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_GererPharmacie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_GererPharmacie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_GererPharmacie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
     
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Admin_GererPharmacie().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete_btn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel nb_pharma_label;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
