/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tunipharma.gui;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import tunipharma.DAO.MessageDAO;
import tunipharma.entities.Message;

/**
 *
 * @author houssem_tmn
 */
public class EnvoieMail extends javax.swing.JFrame {

    /**
     * Creates new form EnvoieMail
     */
    public EnvoieMail() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jmailDest = new javax.swing.JTextField();
        bouttonEvoyer = new javax.swing.JButton();
        jobjet = new java.awt.TextField();
        jMessage = new java.awt.TextArea();
        jMailAdmin = new java.awt.TextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPasswordAdmin = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 590));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jmailDest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmailDestActionPerformed(evt);
            }
        });
        getContentPane().add(jmailDest);
        jmailDest.setBounds(200, 270, 146, 30);

        bouttonEvoyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouttonEvoyerActionPerformed(evt);
            }
        });
        getContentPane().add(bouttonEvoyer);
        bouttonEvoyer.setBounds(380, 450, 120, 40);
        getContentPane().add(jobjet);
        jobjet.setBounds(200, 310, 146, 20);
        getContentPane().add(jMessage);
        jMessage.setBounds(200, 340, 360, 100);

        jMailAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMailAdminActionPerformed(evt);
            }
        });
        getContentPane().add(jMailAdmin);
        jMailAdmin.setBounds(200, 210, 146, 20);

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(450, 10, 140, 30);

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(450, 60, 120, 30);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(460, 510, 130, 40);

        jPasswordAdmin.setText("jPasswordField1");
        getContentPane().add(jPasswordAdmin);
        jPasswordAdmin.setBounds(200, 240, 150, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tunipharma/image/messagerie.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, -160, 660, 890);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bouttonEvoyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouttonEvoyerActionPerformed

        //email
        Pattern patternMail = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@" + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$"
        );
        Matcher matcherMailadmin = patternMail.matcher(jMailAdmin.getText());
        Matcher matcherMailDest = patternMail.matcher(jmailDest.getText());

        if (matcherMailadmin.matches()) {

            if (matcherMailDest.matches()) {

                MessageDAO messageDAO = new MessageDAO();
                Message m = new Message();
                String dest = jmailDest.getText();
                String[] to = {dest};

                m.setMailAdmin(jMailAdmin.getText());

                m.setMessage(jMessage.getText());
                m.setObjet(jobjet.getText());
                m.setPasswordAdmin(jPasswordAdmin.getText());
                messageDAO.envoieMessage(m, to);
                 JOptionPane.showMessageDialog(this, "votre message a été envoyé avec succès");
                 this.setVisible(false);
                 Admin_Accueil accueil =new Admin_Accueil();
                 accueil.setVisible(true);


            } else {
                            JOptionPane.showMessageDialog(this, "adresse mail destinataire invalide");

              

            }

        } else {
  JOptionPane.showMessageDialog(this, "adresse mail admin invalide");
        }


    }//GEN-LAST:event_bouttonEvoyerActionPerformed

    private void jMailAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMailAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMailAdminActionPerformed

    private void jmailDestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmailDestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmailDestActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        bouttonEvoyer.setBorderPainted(false);
        bouttonEvoyer.setContentAreaFilled(false);
        bouttonEvoyer.setFocusPainted(false);
        bouttonEvoyer.setOpaque(false);

        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setFocusPainted(false);
        jButton5.setOpaque(false);

        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setFocusPainted(false);
        jButton6.setOpaque(false);

        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setOpaque(false);

// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.setVisible(true);
        FormProfilAdmin formadmin = new FormProfilAdmin();
        formadmin.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        this.setVisible(false);
        Admin_Connexion adm = new Admin_Connexion();
        adm.setVisible(true);

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        Admin_Accueil accueil = new Admin_Accueil();
        accueil.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnvoieMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnvoieMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnvoieMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnvoieMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnvoieMail().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouttonEvoyer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel6;
    private java.awt.TextField jMailAdmin;
    private java.awt.TextArea jMessage;
    private javax.swing.JPasswordField jPasswordAdmin;
    private javax.swing.JTextField jmailDest;
    private java.awt.TextField jobjet;
    // End of variables declaration//GEN-END:variables
}
