/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tunipharma.gui;

import tunipharma.entities.Admin;
import tunipharma.DAO.AdminDAO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.*;
import javax.swing.JOptionPane;

/**
 *
 * @author imen
 */
public class FormProfilAdmin extends javax.swing.JFrame {

    /**
     * 
     * 
     * Creates new form FormProfilAdmin
     * 
     * 
     * 
     */
    
     List<Admin> admins = new ArrayList<Admin>();
     Admin a;
    
    public FormProfilAdmin()  {
             
            AdminDAO dao =new AdminDAO();
            admins= dao.GetAllAdmin();
            Iterator i = admins.iterator(); 
            while(i.hasNext())
            {
                a = (Admin)i.next();
            }
            
           
            initComponents();
        
         jTextFieldLogin.setText(a.getLogin());
            jTextFieldEmail.setText(a.getEmail());
            jTextFieldPWD.setText(a.getPwd());
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldLogin1 = new javax.swing.JTextField();
        jTextFieldPWD1 = new javax.swing.JTextField();
        jTextFieldEmail1 = new javax.swing.JTextField();
        jButtonModifier1 = new javax.swing.JButton();
        jButtonValider1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldLogin = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jButtonValider = new javax.swing.JButton();
        jTextFieldPWD = new javax.swing.JPasswordField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jFrame1formWindowOpened(evt);
            }
        });

        jLabel5.setText("Login");

        jLabel6.setText("Password");

        jLabel7.setText("Email");

        jButtonModifier1.setText("Modifier");
        jButtonModifier1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifier1ActionPerformed(evt);
            }
        });

        jButtonValider1.setText("Valider");
        jButtonValider1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValider1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addComponent(jButtonModifier1)
                        .addGap(95, 95, 95)
                        .addComponent(jButtonValider1))
                    .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jFrame1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jFrame1Layout.createSequentialGroup()
                            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldEmail1)
                                .addComponent(jTextFieldPWD1)))))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldPWD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModifier1)
                    .addComponent(jButtonValider1))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(605, 590));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jTextFieldLogin.setEditable(false);
        getContentPane().add(jTextFieldLogin);
        jTextFieldLogin.setBounds(270, 220, 129, 30);
        getContentPane().add(jTextFieldEmail);
        jTextFieldEmail.setBounds(270, 300, 132, 30);

        jButtonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonValider);
        jButtonValider.setBounds(240, 420, 120, 40);
        getContentPane().add(jTextFieldPWD);
        jTextFieldPWD.setBounds(270, 260, 129, 30);

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(450, 10, 130, 30);

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(460, 60, 120, 30);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(460, 500, 130, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tunipharma/image/Gerer mon compte.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, -90, 640, 750);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

                
jButtonValider.setBorderPainted(false); 
jButtonValider.setContentAreaFilled(false); 
jButtonValider.setFocusPainted(false); 
jButtonValider.setOpaque(false);

jButton5.setBorderPainted(false); 
jButton5.setContentAreaFilled(false); 
jButton5.setFocusPainted(false); 
jButton5.setOpaque(false);

jButton6.setBorderPainted(false); 
jButton6.setContentAreaFilled(false); 
jButton6.setFocusPainted(false); 
jButton6.setOpaque(false);

jButton1.setBorderPainted(false); 
jButton1.setContentAreaFilled(false); 
jButton1.setFocusPainted(false); 
jButton1.setOpaque(false);




// TODO add your handling code here:
        
        
        /*AdminDAO dao = new AdminDAO();
        try {
            jTextFieldLogin.setText(dao.GetAdmin().getLogin());
            jTextFieldEmail.setText(dao.GetAdmin().getemail());
            jTextFieldPWD.setText(dao.GetAdmin().getpwd());
        } catch (SQLException ex) {
            Logger.getLogger(FormProfilAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }*/
       
      
    }//GEN-LAST:event_formWindowOpened
public static boolean isValid(String email)
{
	if( email!=null && email.trim().length()>0 )
		return email.matches("^[a-zA-Z0-9\\.\\-\\_]+@([a-zA-Z0-9\\-\\_\\.]+\\.)+([a-zA-Z]{2,4})$");
	return false;
}
    
    private void jButtonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderActionPerformed
        // TODO add your handling code here:
        if(isValid(jTextFieldEmail.getText())==true)
        a.setEmail(jTextFieldEmail.getText());
        else
        { JOptionPane.showMessageDialog(null,"Mail Invalide");
          FormProfilAdmin f=new FormProfilAdmin();
          this.setVisible(false);
          f.setVisible(true);
        }
        
        a.setPwd(jTextFieldPWD.getText());
        a.setLogin(jTextFieldLogin.getText());
        
        AdminDAO dao = new AdminDAO();
        dao.ModifierAdmin(a);
        JOptionPane.showMessageDialog(null,"Modification effectué");
        
       this.setVisible(false);
        Admin_Accueil ac =new Admin_Accueil();
        ac.setVisible(true);
        
        
    }//GEN-LAST:event_jButtonValiderActionPerformed

    private void jButtonModifier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifier1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonModifier1ActionPerformed

    private void jButtonValider1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValider1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonValider1ActionPerformed

    private void jFrame1formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrame1formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_jFrame1formWindowOpened

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

         this.setVisible(true);
        FormProfilAdmin formadmin = new FormProfilAdmin();
        formadmin.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
          this.setVisible(false);
        Admin_Connexion adm =new Admin_Connexion();
        adm.setVisible(true);
                
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        Admin_Accueil accueil = new Admin_Accueil();
        accueil.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormProfilAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormProfilAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormProfilAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormProfilAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormProfilAdmin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonModifier1;
    private javax.swing.JButton jButtonValider;
    private javax.swing.JButton jButtonValider1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEmail1;
    private javax.swing.JTextField jTextFieldLogin;
    private javax.swing.JTextField jTextFieldLogin1;
    private javax.swing.JPasswordField jTextFieldPWD;
    private javax.swing.JTextField jTextFieldPWD1;
    // End of variables declaration//GEN-END:variables
}
