/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tunipharma.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import tunipharma.DAO.AddresseDAO;
import tunipharma.DAO.PharmacieDAO;
import tunipharma.DAO.PharmacienDAO;
import tunipharma.entities.Pharmacie;
import tunipharma.entities.Pharmacien;
import tunipharma.entities.Adresse;
import tunipharma.util.ConnectionBD;

/**
 *
 * @author houssem_tmn
 */
public class Pharmacie_inscrit extends javax.swing.JFrame {

    String name;

    /**
     * Creates new form Pharmacie_inscrit
     */
    public Pharmacie_inscrit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel8 = new javax.swing.JLabel();
        delegComboBox = new javax.swing.JComboBox();
        numField = new javax.swing.JSpinner();
        gouverCombox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jgardeArea = new javax.swing.JTextArea();
        ckinfirmerie = new java.awt.Checkbox();
        ckService = new java.awt.Checkbox();
        nuitRadio = new javax.swing.JRadioButton();
        jourRadio = new javax.swing.JRadioButton();
        jMatricule = new javax.swing.JTextField();
        rueField = new javax.swing.JTextField();
        codePField = new javax.swing.JTextField();
        nom_pharmacieText = new javax.swing.JTextField();
        telTextField = new javax.swing.JTextField();
        buttonSinscrire = new javax.swing.JButton();
        photoPharmacie = new javax.swing.JTextField();
        jButton_photo_pharmacien = new javax.swing.JButton();
        buttonSinscrire1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        buttonSinscrire2 = new javax.swing.JButton();

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tunipharma/image/Pharmacien Inscription step1.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 590));
        setPreferredSize(new java.awt.Dimension(605, 590));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        getContentPane().add(delegComboBox);
        delegComboBox.setBounds(260, 270, 100, 20);
        getContentPane().add(numField);
        numField.setBounds(330, 320, 51, 30);

        gouverCombox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gouverComboxActionPerformed(evt);
            }
        });
        getContentPane().add(gouverCombox);
        gouverCombox.setBounds(140, 270, 90, 20);

        jgardeArea.setColumns(20);
        jgardeArea.setRows(5);
        jScrollPane1.setViewportView(jgardeArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(190, 390, 180, 50);

        ckinfirmerie.setLabel("Infirmerie");
        getContentPane().add(ckinfirmerie);
        ckinfirmerie.setBounds(450, 390, 120, 30);

        ckService.setLabel("Service a domicile");
        getContentPane().add(ckService);
        ckService.setBounds(450, 350, 120, 29);

        buttonGroup1.add(nuitRadio);
        nuitRadio.setText(" Nuit");
        getContentPane().add(nuitRadio);
        nuitRadio.setBounds(220, 360, 47, 23);

        buttonGroup1.add(jourRadio);
        jourRadio.setSelected(true);
        jourRadio.setText("Jour");
        getContentPane().add(jourRadio);
        jourRadio.setBounds(90, 360, 47, 23);
        getContentPane().add(jMatricule);
        jMatricule.setBounds(450, 170, 140, 30);
        getContentPane().add(rueField);
        rueField.setBounds(140, 320, 180, 30);
        getContentPane().add(codePField);
        codePField.setBounds(400, 270, 70, 30);
        getContentPane().add(nom_pharmacieText);
        nom_pharmacieText.setBounds(90, 170, 200, 30);

        telTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(telTextField);
        telTextField.setBounds(130, 210, 150, 30);

        buttonSinscrire.setText("Etape suivante");
        buttonSinscrire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSinscrireActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSinscrire);
        buttonSinscrire.setBounds(60, 590, 105, 23);

        photoPharmacie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photoPharmacieActionPerformed(evt);
            }
        });
        getContentPane().add(photoPharmacie);
        photoPharmacie.setBounds(260, 450, 120, 30);

        jButton_photo_pharmacien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_photo_pharmacienActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_photo_pharmacien);
        jButton_photo_pharmacien.setBounds(395, 440, 80, 30);

        buttonSinscrire1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSinscrire1ActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSinscrire1);
        buttonSinscrire1.setBounds(200, 500, 120, 50);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tunipharma/image/Pharmacien Inscription step1.png"))); // NOI18N
        jLabel9.setPreferredSize(new java.awt.Dimension(600, 566));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 810, 560);

        buttonSinscrire2.setText("Etape suivante");
        buttonSinscrire2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSinscrire2ActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSinscrire2);
        buttonSinscrire2.setBounds(0, 0, 105, 23);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void gouverComboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gouverComboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gouverComboxActionPerformed

    private void telTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telTextFieldActionPerformed

    private void buttonSinscrireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSinscrireActionPerformed

        //controle du nom
        String regx = "^[\\p{L} .'-]+$";
        Pattern pattern = Pattern.compile(regx, Pattern.CASE_INSENSITIVE);
        Matcher matcher = pattern.matcher(nom_pharmacieText.getText());

        //contre du numero (aAdresse
        Pattern patternNum = Pattern.compile("\\d[1-5]");
        Matcher matcherNum = patternNum.matcher(numField.getValue().toString());

        //telephone
        Pattern patternPhone = Pattern.compile("^[0-9]{6,12}$");
        Matcher matcherPhone = patternPhone.matcher(telTextField.getText());
        
         //code postal
        Pattern patternCodeP = Pattern.compile("^[0-9]{2,5}$");
        Matcher matcherCodeP = patternCodeP.matcher(codePField.getText());

        if (gouverCombox.getSelectedIndex() == 0) {

            JOptionPane.showMessageDialog(this, "Veuillez choisir la gouvernorat de votre pharmacie");

        } else {

            if (matcherPhone.matches()) {
                
                if(matcherCodeP.matches())
                {
                PharmacieDAO phdao = new PharmacieDAO();
                Pharmacie p = new Pharmacie();
                p.setNom(nom_pharmacieText.getText());

                System.out.println(p.getNom());

                String type = "";
                if (jourRadio.isSelected()) {
                    type = jourRadio.getText();
                }

                if (nuitRadio.isSelected()) {
                    type = nuitRadio.getText();
                }

                p.setType(type);
             //   p.setTel(telTextField.getText());
                p.setJgarde(jgardeArea.getText());

                int infirmerie = 0;
                int servDom = 0;

                if (ckinfirmerie.getState()) {
                    infirmerie = 1;
                }
                p.setInfirmerie(infirmerie);

                if (ckService.getState()) {
                    servDom = 1;
                }
                p.setServDom(servDom);

                p.setMatricule(jMatricule.getText());
                p.setPhoto(Math.random() + name);
                
          ///ouuverture de lafenetre inscription pharmacien et fermeture de cette fenetre
                this.setVisible(false);
                Pharmacien_inscripton pharmacien_inscripton = new Pharmacien_inscripton();
                pharmacien_inscripton.setVisible(true);

        ///controle de saisie
                ///ajout adAdresse               addAdresser = new addrAdresse                AddresseDAO addresseDAO = new AddresseDAO();
Adresse adr =new Adresse();
                
                adr.setGouvernorat(gouverCombox.getSelectedItem().toString());
                adr.setDelegation(delegComboBox.getSelectedItem().toString());
                adr.setCodePostal(codePField.getText());
                adr.setRue(rueField.getText());
                adr.setNumero((int) numField.getValue());
            }
            
            else
            {
                
  JOptionPane.showMessageDialog(this, "Code postale invalide");
            } 
                
            }
            else {
                JOptionPane.showMessageDialog(this, "Numero de telephone invalide");

            }

        }


    }//GEN-LAST:event_buttonSinscrireActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
jButton_photo_pharmacien.setBorderPainted(false); 
jButton_photo_pharmacien.setContentAreaFilled(false); 
jButton_photo_pharmacien.setFocusPainted(false); 
jButton_photo_pharmacien.setOpaque(false);


buttonSinscrire1.setBorderPainted(false); 
buttonSinscrire1.setContentAreaFilled(false); 
buttonSinscrire1.setFocusPainted(false); 
buttonSinscrire1.setOpaque(false);



        




// TODO add your handling code here:

        AddresseDAO addresseDAO = new AddresseDAO();

        List<String> listGouv = addresseDAO.DisplayAllGouvernorat();

        for (String d : listGouv) {
            gouverCombox.addItem(d);

        }
        gouverCombox.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                AddresseDAO adao = new AddresseDAO();
                delegComboBox.removeAllItems();
                List<String> listDeleg = adao.chercherDelegation(gouverCombox.getSelectedItem().toString());

                for (String s : listDeleg) {

                    delegComboBox.addItem(s);
                }

                {

                }
            }
        });

    }//GEN-LAST:event_formWindowOpened

    private void photoPharmacieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photoPharmacieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_photoPharmacieActionPerformed

    private void jButton_photo_pharmacienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_photo_pharmacienActionPerformed
        // TODO add your handling code here:
        //création dun nouveau filechosser
        JFileChooser chooser = new JFileChooser();

        //intitulé du bouton
        chooser.setApproveButtonText("Choix du fichier");
        //affiche la boite de dialogue
        chooser.showOpenDialog(null);
        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            photoPharmacie.setText(chooser.getSelectedFile().getAbsolutePath());
            String chemin = photoPharmacie.getText();
            name = new File(photoPharmacie.getText()).getName();
            System.out.println(name);

        }

        //recuperation du nom

    }//GEN-LAST:event_jButton_photo_pharmacienActionPerformed

    private void buttonSinscrire1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSinscrire1ActionPerformed

        //controle du nom
        String regx = "^[\\p{L} .'-]+$";
        Pattern pattern = Pattern.compile(regx, Pattern.CASE_INSENSITIVE);
        Matcher matcher = pattern.matcher(nom_pharmacieText.getText());

        //contre du numero (aAdresse
            Pattern patternNum = Pattern.compile("\\d[1-5]");
            Matcher matcherNum = patternNum.matcher(numField.getValue().toString());

            //telephone
            Pattern patternPhone = Pattern.compile("^[0-9]{6,12}$");
            Matcher matcherPhone = patternPhone.matcher(telTextField.getText());

            if (gouverCombox.getSelectedIndex() == 0) {

                JOptionPane.showMessageDialog(this, "Veuillez choisir la gouvernorat de votre pharmacie");

            } else {

                if (matcherPhone.matches()) {

                    PharmacieDAO phdao = new PharmacieDAO();
                    Pharmacie p = new Pharmacie();

                    p.setNom(nom_pharmacieText.getText());

                    String type = "";
                    if (jourRadio.isSelected()) {
                        type = jourRadio.getText();
                    }

                    if (nuitRadio.isSelected()) {
                        type = nuitRadio.getText();
                    }

                    p.setType(type);
                    p.setTel(Integer.parseInt(telTextField.getText()));
                    p.setJgarde(jgardeArea.getText());

                    int infirmerie = 0;
                    int servDom = 0;

                    if (ckinfirmerie.getState()) {
                        infirmerie = 1;
                    }
                    p.setInfirmerie(infirmerie);

                    if (ckService.getState()) {
                        servDom = 1;
                    }
                    p.setServDom(servDom);

                    p.setMatricule(jMatricule.getText());
                    p.setPhoto(Math.random() + name);

                    ///ouuverture de lafenetre inscription pharmacien et fermeture de cette fenetre
                    this.setVisible(false);
                    Pharmacien_inscripton pharmacien_inscripton = new Pharmacien_inscripton();
                    pharmacien_inscripton.setVisible(true);

                    ///controle de saisie
                    ///ajout adAdresse               addAdresser = new addrAdresse                AddresseDAO addresseDAO = new AddresseDAO();
                    Adresse adr =new Adresse();

                    adr.setGouvernorat(gouverCombox.getSelectedItem().toString());
                    adr.setDelegation(delegComboBox.getSelectedItem().toString());
                    adr.setCodePostal(codePField.getText());
                    adr.setRue(rueField.getText());
                    adr.setNumero((int) numField.getValue());

                } else {
                    JOptionPane.showMessageDialog(this, "Numero de telephone invalide");

                }

            }

    }//GEN-LAST:event_buttonSinscrire1ActionPerformed

    private void buttonSinscrire2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSinscrire2ActionPerformed

        //controle du nom
        String regx = "^[\\p{L} .'-]+$";
        Pattern pattern = Pattern.compile(regx, Pattern.CASE_INSENSITIVE);
        Matcher matcher = pattern.matcher(nom_pharmacieText.getText());

        //contre du numero (aAdresse
            Pattern patternNum = Pattern.compile("\\d[1-5]");
            Matcher matcherNum = patternNum.matcher(numField.getValue().toString());

            //telephone
            Pattern patternPhone = Pattern.compile("^[0-9]{6,12}$");
            Matcher matcherPhone = patternPhone.matcher(telTextField.getText());

            if (gouverCombox.getSelectedIndex() == 0) {

                JOptionPane.showMessageDialog(this, "Veuillez choisir la gouvernorat de votre pharmacie");

            } else {

                if (matcherPhone.matches()) {

                    PharmacieDAO phdao = new PharmacieDAO();
                    Pharmacie p = new Pharmacie();

                    p.setNom(nom_pharmacieText.getText());

                    String type = "";
                    if (jourRadio.isSelected()) {
                        type = jourRadio.getText();
                    }

                    if (nuitRadio.isSelected()) {
                        type = nuitRadio.getText();
                    }

                    p.setType(type);
                    p.setTel(Integer.parseInt(telTextField.getText()));
                    p.setJgarde(jgardeArea.getText());

                    int infirmerie = 0;
                    int servDom = 0;

                    if (ckinfirmerie.getState()) {
                        infirmerie = 1;
                    }
                    p.setInfirmerie(infirmerie);

                    if (ckService.getState()) {
                        servDom = 1;
                    }
                    p.setServDom(servDom);

                    p.setMatricule(jMatricule.getText());
                    p.setPhoto(Math.random() + name);

                    ///ouuverture de lafenetre inscription pharmacien et fermeture de cette fenetre
                    this.setVisible(false);
                    Pharmacien_inscripton pharmacien_inscripton = new Pharmacien_inscripton();
                    pharmacien_inscripton.setVisible(true);

                    ///controle de saisie
                    ///ajout adAdresse               addAdresser = new addrAdresse                AddresseDAO addresseDAO = new AddresseDAO();
                    Adresse adr =new Adresse();

                    adr.setGouvernorat(gouverCombox.getSelectedItem().toString());
                    adr.setDelegation(delegComboBox.getSelectedItem().toString());
                    adr.setCodePostal(codePField.getText());
                    adr.setRue(rueField.getText());
                    adr.setNumero((int) numField.getValue());

                } else {
                    JOptionPane.showMessageDialog(this, "Numero de telephone invalide");

                }

            }

    }//GEN-LAST:event_buttonSinscrire2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pharmacie_inscrit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pharmacie_inscrit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pharmacie_inscrit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pharmacie_inscrit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pharmacie_inscrit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonSinscrire;
    private javax.swing.JButton buttonSinscrire1;
    private javax.swing.JButton buttonSinscrire2;
    private java.awt.Checkbox ckService;
    private java.awt.Checkbox ckinfirmerie;
    private javax.swing.JTextField codePField;
    private javax.swing.JComboBox delegComboBox;
    private javax.swing.JComboBox gouverCombox;
    private javax.swing.JButton jButton_photo_pharmacien;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jMatricule;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jgardeArea;
    private javax.swing.JRadioButton jourRadio;
    private javax.swing.JTextField nom_pharmacieText;
    private javax.swing.JRadioButton nuitRadio;
    private javax.swing.JSpinner numField;
    private javax.swing.JTextField photoPharmacie;
    private javax.swing.JTextField rueField;
    private javax.swing.JTextField telTextField;
    // End of variables declaration//GEN-END:variables
}
