package tunipharma.gui;

//testgit
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Panel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.channels.FileChannel;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicOptionPaneUI;
import tunipharma.DAO.AddresseDAO;
import tunipharma.DAO.PharmacieDAO;
import tunipharma.DAO.PharmacienDAO;
import tunipharma.entities.Pharmacie;
import tunipharma.entities.Pharmacien;
import tunipharma.entities.Adresse;

/**
 *
 * @author Cyrine
 */
public class Pharmacien_inscripton extends javax.swing.JFrame {

   
   
            
    String name1;

    /**
     * Creates new form Pharmacien_inscripton
     */
    public Pharmacien_inscripton() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        nomText = new javax.swing.JTextField();
        prenomText = new javax.swing.JTextField();
        telText = new javax.swing.JTextField();
        emailText = new javax.swing.JTextField();
        loginText = new javax.swing.JTextField();
        jButton_photo_pharmacien = new javax.swing.JButton();
        buttonSinscrire = new javax.swing.JButton();
        photo = new javax.swing.JTextField();
        label4 = new java.awt.Label();
        mdpText = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 590));
        setMinimumSize(new java.awt.Dimension(600, 590));
        setPreferredSize(new java.awt.Dimension(600, 590));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        nomText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomTextActionPerformed(evt);
            }
        });
        getContentPane().add(nomText);
        nomText.setBounds(160, 170, 132, 30);

        prenomText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenomTextActionPerformed(evt);
            }
        });
        getContentPane().add(prenomText);
        prenomText.setBounds(160, 210, 132, 30);

        telText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telTextActionPerformed(evt);
            }
        });
        getContentPane().add(telText);
        telText.setBounds(160, 250, 132, 30);

        emailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextActionPerformed(evt);
            }
        });
        getContentPane().add(emailText);
        emailText.setBounds(160, 290, 132, 30);

        loginText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginTextActionPerformed(evt);
            }
        });
        getContentPane().add(loginText);
        loginText.setBounds(160, 330, 132, 30);

        jButton_photo_pharmacien.setAlignmentX(0.5F);
        jButton_photo_pharmacien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_photo_pharmacienActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_photo_pharmacien);
        jButton_photo_pharmacien.setBounds(390, 390, 90, 40);
        jButton_photo_pharmacien.getAccessibleContext().setAccessibleName("Parcourir_pharmacien");

        buttonSinscrire.setAlignmentX(0.5F);
        buttonSinscrire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSinscrireActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSinscrire);
        buttonSinscrire.setBounds(200, 493, 120, 40);

        photo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photoActionPerformed(evt);
            }
        });
        getContentPane().add(photo);
        photo.setBounds(270, 400, 100, 30);
        photo.getAccessibleContext().setAccessibleName("status");

        label4.setText("label4");
        getContentPane().add(label4);
        label4.setBounds(1461, 598, 38, 20);

        mdpText.setText("jPasswordField1");
        getContentPane().add(mdpText);
        mdpText.setBounds(160, 370, 132, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tunipharma/image/Pharmacien Inscription step2.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 563);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomTextActionPerformed

    private void jButton_photo_pharmacienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_photo_pharmacienActionPerformed
        // TODO add your handling code here:
        //création dun nouveau filechosser
        JFileChooser chooser = new JFileChooser();

//intitulé du bouton
        chooser.setApproveButtonText("Choix du fichier");
//affiche la boite de dialogue 
        chooser.showOpenDialog(null);
        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            photo.setText(chooser.getSelectedFile().getAbsolutePath());
            name1 = new File(photo.getText()).getName();
            System.out.println(name1);

        }

//panel.add(new JLabel(new ImageIcon(getClass().getResource(".//dm.jpg"))));

    }//GEN-LAST:event_jButton_photo_pharmacienActionPerformed

    private void buttonSinscrireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSinscrireActionPerformed

        //controle du nom
        String regx = "^[\\p{L} .'-]+$";
        Pattern pattern = Pattern.compile(regx, Pattern.CASE_INSENSITIVE);
        Matcher matcher = pattern.matcher(nomText.getText());

        //telephone
        Pattern patternPhone = Pattern.compile("^[0-9]{6,12}$");
        Matcher matcherPhone = patternPhone.matcher(telText.getText());

        //email
        Pattern patternMail = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@" + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$"
        );
        Matcher matcherMail = patternMail.matcher(emailText.getText());

        if (matcherMail.matches()) {

            if (matcherPhone.matches()) {

                AddresseDAO addresseDAO = new AddresseDAO();
              Adresse adr = new Adresse();
                int id_addresse = addresseDAO.insertAddresse(adr);

                PharmacieDAO pharmacieDAO = new PharmacieDAO();
                Pharmacie p = new Pharmacie();
                //affectation de l'id de l'addresee
                p.setId_adresse(id_addresse);
                //ajout de la pharmacie
                pharmacieDAO.insertPharmacie(p);

                //pharmacien
                PharmacienDAO pharmacienDAO = new PharmacienDAO();
                Pharmacien pharmacien = new Pharmacien();

                pharmacien.setNom(nomText.getText());
                pharmacien.setPrenom(prenomText.getText());
                pharmacien.setEmail(emailText.getText());
                pharmacien.setTel(telText.getText());
                pharmacien.setLogin(loginText.getText());
                pharmacien.setPwd(mdpText.getText());
                pharmacien.setPhoto(Math.random() + name1);

                pharmacienDAO.insertPharmacien(pharmacien, p.getMatricule());

                //copie de l'image de pharmacien vers le dossier img-parmacien
                String url = photo.getText();

                FileChannel in = null; // canal d'entrée
                FileChannel out = null; // canal de sortie

                try {
                    // Init
                    in = new FileInputStream(url).getChannel();
                    if (url.endsWith(".jpg")) {
                        out = new FileOutputStream(".\\img-pharmacien\\" + name1 + Math.random() + ".jpg").getChannel();
                    } else if (url.endsWith(".jpeg")) {
                        out = new FileOutputStream(".\\img-pharmacien\\" + name1 + Math.random() + "jpeg").getChannel();
                    } else if (url.endsWith(".png")) {
                        out = new FileOutputStream(".\\img-pharmacien\\" + name1 + Math.random() + ".png").getChannel();
                    } else {
                        System.out.print("Type d'image invalide");
                    }

                    // Copie depuis le in vers le out
                    in.transferTo(0, in.size(), out);
                } catch (Exception e) {
                    e.printStackTrace(); // n'importe quelle exception
                } finally { // finalement on ferme
                    if (in != null) {
                        try {
                            in.close();
                        } catch (IOException e) {
                        }
                    }
                    if (out != null) {
                        try {
                            out.close();
                        } catch (IOException e) {
                        }
                    }
                }

        //copie de l'image de pharmacie dans img
                //copie de l'image de pharmacien vers le dossier img-parmacien
                String url2 = p.getPhoto();

                FileChannel in1 = null; // canal d'entrée
                FileChannel out1 = null; // canal de sortie

                try {
                    // Init
                    in = new FileInputStream(url).getChannel();
                    if (url.endsWith(".jpg")) {
                        out = new FileOutputStream(".\\img-pharmacie\\" + p.getPhoto() + ".jpg").getChannel();
                    } else if (url.endsWith(".jpeg")) {
                        out = new FileOutputStream(".\\img-pharmacie\\" + p.getPhoto() + "jpeg").getChannel();
                    } else if (url.endsWith(".png")) {
                        out = new FileOutputStream(".\\img-pharmacie\\" + p.getPhoto() + ".png").getChannel();
                    } else {
                        System.out.print("Type d'image invalide");
                    }

                    // Copie depuis le in vers le out
                    in.transferTo(0, in.size(), out);
                } catch (Exception e) {
                    e.printStackTrace(); // n'importe quelle exception
                } finally { // finalement on ferme
                    if (in != null) {
                        try {
                            in.close();
                        } catch (IOException e) {
                        }
                    }
                    if (out != null) {
                        try {
                            out.close();
                        } catch (IOException e) {
                        }
                    }
                }
            
            
             JOptionPane.showMessageDialog(this, "Ajout effectué avec succès");
             this.setVisible(false);
             Admin_Connexion ac =new  Admin_Connexion();
             ac.setVisible(true);
            
            
            } else {
                JOptionPane.showMessageDialog(this, "Numero de telephone invalide");

            }

        } else {
            JOptionPane.showMessageDialog(this, "adresse mail invalide");
        }

        /*  JOptionPane.showMessageDialog(this, "ajout effectué");*/

    }//GEN-LAST:event_buttonSinscrireActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
jButton_photo_pharmacien.setBorderPainted(false); 
jButton_photo_pharmacien.setContentAreaFilled(false); 
jButton_photo_pharmacien.setFocusPainted(false); 
jButton_photo_pharmacien.setOpaque(false);


buttonSinscrire.setBorderPainted(false); 
buttonSinscrire.setContentAreaFilled(false); 
buttonSinscrire.setFocusPainted(false); 
buttonSinscrire.setOpaque(false);





    }//GEN-LAST:event_formWindowOpened

    private void photoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_photoActionPerformed

    private void telTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telTextActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_telTextActionPerformed

    private void prenomTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenomTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenomTextActionPerformed

    private void loginTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginTextActionPerformed

    private void emailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pharmacien_inscripton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pharmacien_inscripton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pharmacien_inscripton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pharmacien_inscripton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pharmacien_inscripton().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonSinscrire;
    private javax.swing.JTextField emailText;
    private javax.swing.JButton jButton_photo_pharmacien;
    private javax.swing.JLabel jLabel1;
    private java.awt.Label label4;
    private javax.swing.JTextField loginText;
    private javax.swing.JPasswordField mdpText;
    private javax.swing.JTextField nomText;
    private javax.swing.JTextField photo;
    private javax.swing.JTextField prenomText;
    private javax.swing.JTextField telText;
    // End of variables declaration//GEN-END:variables
}
