/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tunipharma.gui;

import javax.swing.JOptionPane;
import org.jfree.ui.RefineryUtilities;
import tunipharma.DAO.*;
import tunipharma.entities.BarChart;
import tunipharma.statistique.PieChartJG;

/**
 *
 * @author imen
 */
public class Stat extends javax.swing.JFrame {

    /**
     * Creates new form Stat
     */
    public Stat() {
        initComponents();
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
        btgrp.add(rbtn1);
        rbtn1.setSelected(true);
        btgrp.add(rbtn2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgrp = new javax.swing.ButtonGroup();
        cbx_type_stat = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        rbtn1 = new javax.swing.JRadioButton();
        rbtn2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbx_type_stat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "------", "Par Région", "Par Jour de Garde", "Nuit/Jour" }));
        cbx_type_stat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_type_statActionPerformed(evt);
            }
        });
        getContentPane().add(cbx_type_stat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 163, 20));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 365, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 77, -1, -1));

        rbtn1.setText("PieChart");
        getContentPane().add(rbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 33, -1, 20));

        rbtn2.setText("BarChart");
        getContentPane().add(rbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 33, -1, 20));

        jLabel2.setText("Statistique :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 60, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int res[];
        switch(cbx_type_stat.getSelectedIndex()){
            case 1 :{
                if(rbtn1.isSelected()){
                   JOptionPane.showMessageDialog(null, "PieChart Pharmacies par Region !\nComing Soon !");
                }
                if(rbtn2.isSelected()){
                   JOptionPane.showMessageDialog(null, "BarChart Pharmacies par Region !\nComing Soon !");     
                }   
            ;break;}
            case 2 :{
                if(rbtn1.isSelected()){
                    PieChartJG demoP = new PieChartJG("Statistique Pharmacies Par Jour de Garde", "Statistique Pharmacies Par Jour de Garde");
                    demoP.pack();
                    RefineryUtilities.centerFrameOnScreen(demoP);
                    demoP.setVisible(true);
                }
                if(rbtn2.isSelected()){
                    final tunipharma.statistique.BarChartJG demoB = new tunipharma.statistique.BarChartJG("Statistique Pharmacies Par Jour de Garde");
                    demoB.pack();
                    RefineryUtilities.centerFrameOnScreen(demoB);
                    demoB.setVisible(true);   
                }
            ;break;}
            case 3 :{
                if(rbtn1.isSelected()){
                    
                }
                if(rbtn2.isSelected()){
                        
                }
            ;break; }   
            default : {
                JOptionPane.showMessageDialog(null, "Veuillez selectionner une Statistique !");
            }
        }        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbx_type_statActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_type_statActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_type_statActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgrp;
    private javax.swing.JComboBox cbx_type_stat;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbtn1;
    private javax.swing.JRadioButton rbtn2;
    // End of variables declaration//GEN-END:variables
}
